version: "3.8"
services:

  db:
    image: postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
    restart: always
    networks:
      - private

  node:
    image: node:12
    user: node
    working_dir: /home/node/app
    environment:
      NODE_ENV: production
      PORT: 8080
      DB_URL: postgresql://postgres:secret@db:5432/postgres?schema=public
      JWT_SECRET: xxxxxxxx
      ADMIN_EMAIL: admin@localhost.com
      ADMIN_PASSWORD: admin
    volumes:
      - ./:/home/node/app
    expose:
      - 8080 
    ports:
      - 81:8080
    command: bash -c 'rm -rf node_modules && npm install && npm start'
    depends_on:
      - db
    networks:
      - public
      - private

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 80:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: always

volumes: # Persistencia de datos
  pgadmin_data:

networks:
  public:
    internal: false
  private:
    internal: true
